/**
 * Error Codes
 * 
 * This module defines error codes used throughout the application.
 * Only includes generic error codes and module-specific error codes.
 * 
 * Modules:
 * - Auth, Onboarding, Dashboard, Reports, Consents, Notifications, 
 *   Clinical Analytics, Visits, Profile (Phase 1)
 * - Prescriptions, Appointments (Phase 2)
 */

export const ErrorCodes = {
  // ============================================
  // Generic Error Codes
  // ============================================
  GENERIC_ERROR: 'GENERIC_ERROR',
  
  // HTTP Status Code Errors (4xx)
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
  // HTTP Status Code Errors (5xx)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  BAD_GATEWAY: 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  
  // Generic Validation Errors
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_FORMAT: 'INVALID_FORMAT',
  VALUE_TOO_LONG: 'VALUE_TOO_LONG',
  VALUE_TOO_SHORT: 'VALUE_TOO_SHORT',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_DATE: 'INVALID_DATE',
  
  // ============================================
  // Module-Specific Error Codes
  // ============================================
  
  // Auth Module
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  
  // Onboarding Module
  ONBOARDING_INCOMPLETE: 'ONBOARDING_INCOMPLETE',
  ONBOARDING_ALREADY_COMPLETED: 'ONBOARDING_ALREADY_COMPLETED',
  
  // Dashboard Module
  DASHBOARD_DATA_UNAVAILABLE: 'DASHBOARD_DATA_UNAVAILABLE',
  
  // Reports Module
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_UPLOAD_FAILED: 'REPORT_UPLOAD_FAILED',
  REPORT_DELETE_FAILED: 'REPORT_DELETE_FAILED',
  REPORT_ACCESS_DENIED: 'REPORT_ACCESS_DENIED',
  
  // Consents Module
  CONSENT_NOT_FOUND: 'CONSENT_NOT_FOUND',
  CONSENT_ALREADY_EXISTS: 'CONSENT_ALREADY_EXISTS',
  CONSENT_REQUEST_DENIED: 'CONSENT_REQUEST_DENIED',
  CONSENT_ALREADY_GRANTED: 'CONSENT_ALREADY_GRANTED',
  CONSENT_ALREADY_REJECTED: 'CONSENT_ALREADY_REJECTED',
  
  // Notifications Module
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_MARK_READ_FAILED: 'NOTIFICATION_MARK_READ_FAILED',
  
  // Clinical Analytics Module
  ANALYTICS_DATA_UNAVAILABLE: 'ANALYTICS_DATA_UNAVAILABLE',
  ANALYTICS_QUERY_INVALID: 'ANALYTICS_QUERY_INVALID',
  
  // Visits Module
  VISIT_NOT_FOUND: 'VISIT_NOT_FOUND',
  VISIT_CREATE_FAILED: 'VISIT_CREATE_FAILED',
  VISIT_UPDATE_FAILED: 'VISIT_UPDATE_FAILED',
  VISIT_DELETE_FAILED: 'VISIT_DELETE_FAILED',
  
  // Profile Module
  PROFILE_SECTION_NOT_FOUND: 'PROFILE_SECTION_NOT_FOUND',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  
  // Prescriptions Module (Phase 2)
  PRESCRIPTION_NOT_FOUND: 'PRESCRIPTION_NOT_FOUND',
  PRESCRIPTION_CREATE_FAILED: 'PRESCRIPTION_CREATE_FAILED',
  PRESCRIPTION_UPDATE_FAILED: 'PRESCRIPTION_UPDATE_FAILED',
  
  // Appointments Module (Phase 2)
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_CONFLICT: 'APPOINTMENT_CONFLICT',
  APPOINTMENT_CREATE_FAILED: 'APPOINTMENT_CREATE_FAILED',
  APPOINTMENT_UPDATE_FAILED: 'APPOINTMENT_UPDATE_FAILED',
  APPOINTMENT_CANCEL_FAILED: 'APPOINTMENT_CANCEL_FAILED',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

